#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-aliyun-oss-java-sdk
Version  : 2.8.3
Release  : 2
URL      : https://github.com/aliyun/aliyun-oss-java-sdk/archive/2.8.3.tar.gz
Source0  : https://github.com/aliyun/aliyun-oss-java-sdk/archive/2.8.3.tar.gz
Source1  : https://repo1.maven.org/maven2/com/aliyun/oss/aliyun-sdk-oss/2.8.3/aliyun-sdk-oss-2.8.3.jar
Source2  : https://repo1.maven.org/maven2/com/aliyun/oss/aliyun-sdk-oss/2.8.3/aliyun-sdk-oss-2.8.3.pom
Source3  : https://repo1.maven.org/maven2/com/aliyun/oss/aliyun-sdk-oss/3.4.1/aliyun-sdk-oss-3.4.1.jar
Source4  : https://repo1.maven.org/maven2/com/aliyun/oss/aliyun-sdk-oss/3.4.1/aliyun-sdk-oss-3.4.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-aliyun-oss-java-sdk-data = %{version}-%{release}

%description
# Aliyun OSS SDK for Java
[![GitHub version](https://badge.fury.io/gh/aliyun%2Faliyun-oss-java-sdk.svg)](https://badge.fury.io/gh/aliyun%2Faliyun-oss-java-sdk)
[![Build Status](https://travis-ci.org/aliyun/aliyun-oss-java-sdk.svg?branch=master)](https://travis-ci.org/aliyun/aliyun-oss-java-sdk)

%package data
Summary: data components for the mvn-aliyun-oss-java-sdk package.
Group: Data

%description data
data components for the mvn-aliyun-oss-java-sdk package.


%prep
%setup -q -n aliyun-oss-java-sdk-2.8.3

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/2.8.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/2.8.3/aliyun-sdk-oss-2.8.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/2.8.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/2.8.3/aliyun-sdk-oss-2.8.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/3.4.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/3.4.1/aliyun-sdk-oss-3.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/3.4.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/3.4.1/aliyun-sdk-oss-3.4.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/2.8.3/aliyun-sdk-oss-2.8.3.jar
/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/2.8.3/aliyun-sdk-oss-2.8.3.pom
/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/3.4.1/aliyun-sdk-oss-3.4.1.jar
/usr/share/java/.m2/repository/com/aliyun/oss/aliyun-sdk-oss/3.4.1/aliyun-sdk-oss-3.4.1.pom
